services:
  php-fpm:
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app

  nginx:
    build:
      dockerfile: nginx.Dockerfile
    image: nginx:1.23.0
    ports:
      - "8000:8080"
    volumes:
      - ./.gitignore:/var/www/app/public/.gitignore
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - php-fpm